default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: blooming_record_development

test:
  <<: *default
  database: blooming_record_test
